baseurl = "https://docs.astralbot.io"
languageCode = "en-us"
title = "Astral Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Astral"
	description = "Next generation Cloud Bot."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "deviouspk"
	email   = "info@astralbot.io"

[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 2

[[menu.main]]
    name   = "RS Accounts"
    url    = "accounts/"
    weight = 3

[[menu.main]]
    name   = "Proxies"
    url    = "proxies/"
    weight = 4

[[menu.main]]
    name   = "Machines"
    url    = "machines/"
    weight = 5

[[menu.main]]
    name   = "Bots"
    url    = "bots/"
    weight = 6

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Script Api"
	url    = "api/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
